baseURL: "https://markau.dev/"
languageCode: "en-us"
title: "markau.dev"
theme: "markau-theme"
author: "Martin Kauppinen"
copyright: "© 2025 Martin Kauppinen"
enableGitInfo: true

params:
  socialLinks:
    - title: "Mastodon"
      url: "https://tech.lgbt/@fyvec"
      icon: "fa-brands fa-mastodon"
      rel: "me"

    - title: "GitHub"
      url: "https://github.com/martinkauppinen/"
      icon: "fa-brands fa-github"

    - title: "Email"
      url: "mailto:martin.kauppinen+markau.dev@gmail.com"
      icon: "fa-solid fa-envelope"

    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/martin-kauppinen-a32256138"
      icon: "fa-brands fa-linkedin"

    - title: "RSS Feed"
      url: "https://markau.dev/posts/index.xml"
      icon: "fa-solid fa-square-rss"

  about:
    title: "markau.dev"
    description: "Musings when the muse sings"

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
    - identifier: "about"
      name: "About"
      url: "/about/"
    - identifier: "series"
      name: "Series"
      url: "/series/"

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"

markup:
  highlight:
    style: "gruvbox"

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
