baseURL: "https://markau.dev/"
languageCode: "en-us"
title: "markau.dev"
theme: "risotto"
author: "Martin Kauppinen"
copyright: "© 2022 Martin Kauppinen"
enableGitInfo: true

params:
  theme:
    palette: "gruvbox-dark"
    mode: "dark-mode"
  custom_css:
    - "css/custom.css"
  socialLinks:
    - title: "GitHub"
      url: "https://github.com/martinkauppinen/"

    - title: "Email"
      url: "mailto:martin.kauppinen+markau.dev@gmail.com"

    - title: "LinkedIn"
      url: "https://www.linkedin.com/in/martin-kauppinen-a32256138"

    - title: "RSS Feed"
      url: "https://markau.dev/posts/index.xml"

  about:
    title: "markau.dev"
    description: "Musings when the muse sings"

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
    - identifier: "about"
      name: "About"
      url: "/about/"
    - identifier: "series"
      name: "Series"
      url: "/series/"

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
